name: Daily Marketing Data Pipeline
on:
  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Đã update lên v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Đã update lên v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pipeline Script
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          FB_ACCOUNT_ID: ${{ secrets.FB_ACCOUNT_ID }}
          GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
          GCP_PROJECT_ID: "ahb-dltxgg-bigquery"
          GCP_CLIENT_EMAIL: "dlt-bigquery-pusher@ahb-dltxgg-bigquery.iam.gserviceaccount.com"
        run: python backfill.py
